- name: Install s3cmd
  apt: name=s3cmd state=latest

- name: Add configuration for s3cmd including credentials
  template: >
    src=../templates/s3cfg.j2
    dest=~{{ s3cmd_user }}/.s3cfg
    owner={{ s3cmd_user }}
    mode=600
